-- AlterTable
ALTER TABLE "Choices" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "published_at" SET DATA TYPE TIMESTAMP,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMP;
